defaults:
  - model: videovaeplus
  - dataset: solo_pose
  - loss: mse

training:
  device: cpu
  epochs: 100
  batch_size: 64
  learning_rate: 0.0001
  weight_decay: 0.00001
  gradient_clipping: 1.0
  early_stopping: 10